const STUDENT_QUESTION_COUNT = 20;

const QUESTION_BANK = [
    { id: 1, question: 'Perangkat lunak yang biasanya digunakan untuk mengelola MikroTik secara GUI adalah...', answer: 'b', options: ['A. Putty', 'B. WinBox', 'C. VLC', 'D. FileZilla', 'E. Notepad++'], pembahasan: 'WinBox adalah aplikasi GUI resmi MikroTik untuk mengelola router. Putty digunakan untuk akses SSH/Telnet/Serial, bukan aplikasi GUI khusus MikroTik.' },
    { id: 2, question: 'Fungsi utama Identity pada router MikroTik adalah...', answer: 'a', options: ['A. Menentukan nama unik router agar mudah dikenali', 'B. Mengubah kecepatan CPU', 'C. Menghapus seluruh konfigurasi', 'D. Mengunci port Ethernet', 'E. Menambah bandwidth internet'], pembahasan: 'Identity hanya memberi nama unik pada router agar mudah dikenali di jaringan. Identitas tidak memengaruhi performa, keamanan, atau fungsi lainnya.' },
    { id: 3, question: 'Username default MikroTik yang sering dipakai saat pertama kali login adalah...', answer: 'b', options: ['A. root', 'B. admin', 'C. user', 'D. supervisor', 'E. guest'], pembahasan: 'Saat pertama kali diakses, MikroTik default menggunakan username "admin" tanpa password.' },
    { id: 4, question: 'Tujuan utama mengganti password router MikroTik adalah...', answer: 'c', options: ['A. Membuat router lebih cepat', 'B. Menambah fungsi router', 'C. Menjaga keamanan akses administrasi', 'D. Membatasi bandwidth client', 'E. Memperbaiki koneksi DNS'], pembahasan: 'Password melindungi akses administrasi router dari orang yang tidak berwenang agar konfigurasi tidak diubah tanpa izin.' },
    { id: 5, question: 'Fungsi DNS pada router adalah...', answer: 'b', options: ['A. Mengubah alamat MAC', 'B. Menerjemahkan nama domain menjadi alamat IP', 'C. Membagi koneksi internet', 'D. Mengganti topologi jaringan', 'E. Menyimpan file konfigurasi'], pembahasan: 'DNS (Domain Name System) menerjemahkan nama domain menjadi alamat IP sehingga perangkat bisa saling terhubung.' },
    { id: 6, question: 'Ketika Allow Remote Requests pada DNS aktif, artinya router dapat...', answer: 'b', options: ['A. Menyimpan data secara otomatis', 'B. Melayani permintaan DNS dari client jaringan lokal', 'C. Menghapus file .mp3', 'D. Menjalankan hotspot', 'E. Menyunting tabel routing'], pembahasan: 'Allow Remote Requests mengizinkan client jaringan lokal memakai router sebagai DNS server untuk menerjemahkan nama domain.' },
    { id: 7, question: 'NTP Client pada MikroTik berfungsi untuk...', answer: 'a', options: ['A. Menyinkronkan waktu router dengan server waktu', 'B. Mengatur DNS Server', 'C. Mengatur IP Public', 'D. Membuat user profile', 'E. Menghapus firewall rule'], pembahasan: 'NTP Client menyinkronkan jam router dengan server waktu sehingga log, sertifikat, dan jadwal router akurat.' },
    { id: 8, question: 'Jika router tidak memiliki waktu yang benar, dampaknya adalah...', answer: 'b', options: ['A. Router akan otomatis restart', 'B. Log dan pengaturan jadwal bisa tidak akurat', 'C. Port Ethernet mati', 'D. DNS akan menurun secara otomatis', 'E. Router akan mengubah IP public'], pembahasan: 'Waktu yang salah membuat catatan log, penjadwalan, dan proses yang bergantung waktu menjadi tidak konsisten.' },
    { id: 9, question: 'Interface yang biasanya digunakan sebagai koneksi internet pada MikroTik adalah...', answer: 'd', options: ['A. ether1', 'B. wlan1', 'C. bridge1', 'D. ether3', 'E. loopback'], pembahasan: 'Pada topologi praktikum, koneksi internet dihubungkan melalui ether3 sebagai interface WAN, sedangkan ether2 dipakai untuk LAN.' },
    { id: 10, question: 'DHCP Client pada interface WAN berfungsi untuk...', answer: 'a', options: ['A. Menerima IP, gateway, dan DNS otomatis dari ISP', 'B. Melakukan pengaturan IP statis ke client', 'C. Menghapus semua IP lokal', 'D. Menonaktifkan firewall', 'E. Membuat bridge baru'], pembahasan: 'DHCP Client pada interface WAN meminta konfigurasi IP, gateway, dan DNS secara otomatis dari ISP.' },
    { id: 11, question: 'Route default dengan prefix 0.0.0.0/0 berfungsi untuk...', answer: 'a', options: ['A. Mengarahkan lalu lintas yang tidak diketahui ke gateway utama', 'B. Mengunci jaringan lokal', 'C. Menambah user hotspot', 'D. Membatasi alamat MAC', 'E. Menyalakan NTP Client'], pembahasan: 'Route default 0.0.0.0/0 mengirimkan semua lalu lintas yang tidak cocok dengan route lain ke gateway utama (internet).' },
    { id: 12, question: 'Tujuan utama NAT Masquerade adalah...', answer: 'a', options: ['A. Mengubah IP privat client menjadi IP publik saat keluar internet', 'B. Menghubungkan dua router tanpa IP', 'C. Mendeteksi virus', 'D. Menentukan waktu router', 'E. Membatasi jumlah user hotspot'], pembahasan: 'NAT Masquerade menyamarkan IP privat client menjadi IP publik router saat mengakses internet.' },
    { id: 13, question: 'Jika router sudah mendapat IP dari ISP, namun client tidak bisa internet, kemungkinan penyebab utama adalah...', answer: 'a', options: ['A. NAT Masquerade belum dibuat', 'B. DHCP Server sudah aktif', 'C. Router kehilangan IP WAN', 'D. DNS terlalu cepat', 'E. Semua interface nonaktif'], pembahasan: 'Router dengan IP WAN tetapi tanpa aturan NAT masquerade tidak akan meneruskan akses internet ke client LAN.' },
    { id: 14, question: 'DHCP Server pada MikroTik biasanya digunakan untuk...', answer: 'b', options: ['A. Menyaring website', 'B. Memberikan IP secara otomatis kepada client', 'C. Mengganti port WAN', 'D. Menutup semua koneksi WiFi', 'E. Menetapkan password router'], pembahasan: 'DHCP Server membagikan alamat IP beserta gateway dan DNS secara otomatis kepada client.' },
    { id: 15, question: 'IP Pool pada MikroTik berfungsi sebagai...', answer: 'a', options: ['A. Daftar IP yang dapat dipinjamkan ke client DHCP', 'B. Area penyimpanan router', 'C. Kumpulan password hotspot', 'D. Nama user WiFi', 'E. Daftar firewall rule'], pembahasan: 'IP Pool adalah kumpulan alamat yang disediakan DHCP Server untuk dipinjamkan (lease) ke client.' },
    { id: 16, question: 'Hotspot di MikroTik biasanya digunakan untuk...', answer: 'b', options: ['A. Menghubungkan router ke internet', 'B. Membuat sistem autentikasi user sebelum akses jaringan', 'C. Menurunkan kecepatan CPU', 'D. Menyimpan semua DNS', 'E. Menentukan alamat gateway ISP'], pembahasan: 'Hotspot mengharuskan user masuk (login) terlebih dahulu melalui captive portal sebelum dapat menggunakan jaringan.' },
    { id: 17, question: 'Halaman login yang muncul sebelum user masuk jaringan disebut...', answer: 'a', options: ['A. Captive Portal', 'B. DNS Cache', 'C. NAT Forward', 'D. SSH Tunnel', 'E. Bridge Mode'], pembahasan: 'Captive Portal adalah halaman login yang otomatis muncul sebelum user diizinkan mengakses jaringan.' },
    { id: 18, question: 'User Profile pada Hotspot berfungsi untuk...', answer: 'a', options: ['A. Menentukan aturan akses dan pembatasan bandwidth', 'B. Mengubah nomor seri router', 'C. Memperbaiki kabel UTP', 'D. Menentukan gateway default', 'E. Menyimpan hasil ping'], pembahasan: 'User Profile menentukan kecepatan (rate limit), batas waktu, dan kebijakan akses user hotspot.' },
    { id: 19, question: 'Rate Limit pada MikroTik biasanya digunakan untuk...', answer: 'a', options: ['A. Menentukan batas kecepatan upload/download', 'B. Membatasi jumlah user', 'C. Menghidupkan DHCP', 'D. Menyusun daftar menu', 'E. Mengubah alamat IP router'], pembahasan: 'Rate Limit membatasi kecepatan maksimum upload dan download untuk user atau layanan tertentu.' },
    { id: 20, question: 'Penggunaan Hotspot akan lebih tepat diterapkan pada jaringan yang memiliki tujuan...', answer: 'a', options: ['A. Mengontrol akses user melalui autentikasi', 'B. Menambah DNS secara manual', 'C. Menghapus packet filter', 'D. Mengaktifkan proxy FTP', 'E. Mengganti gateway ISP'], pembahasan: 'Hotspot cocok bila tujuan jaringannya adalah mengontrol akses melalui autentikasi, seperti Wi-Fi publik atau berbayar.' },
    { id: 21, question: 'Firewall Filter Chain Input biasanya menangani paket yang ditujukan untuk...', answer: 'a', options: ['A. Router itu sendiri', 'B. Internet luar', 'C. Hanya DNS', 'D. Hanya IP Pool', 'E. Hanya NTP Client'], pembahasan: 'Chain Input memeriksa paket yang ditujukan ke alamat router itu sendiri (paket masuk ke router).' },
    { id: 22, question: 'Firewall Filter Chain Forward biasanya memeriksa paket yang...', answer: 'a', options: ['A. Dikirim dari satu segmen ke segmen lain atau internet', 'B. Hanya untuk router', 'C. Hanya untuk DNS', 'D. Berlangsung dalam satu jaringan lokal saja', 'E. Hanya untuk user hotspot'], pembahasan: 'Chain Forward memeriksa paket yang diteruskan (routed) dari satu interface ke interface lain menuju segmen atau internet.' },
    { id: 23, question: 'ICMP adalah protokol yang umum dipakai untuk...', answer: 'a', options: ['A. Ping dan pengecekan konektivitas', 'B. Mengatur DHCP server', 'C. Memblokir file MP3', 'D. Menentukan bandwidth', 'E. Menangani DNS cache'], pembahasan: 'ICMP (Internet Control Message Protocol) dipakai oleh ping untuk mengecek konektivitas dan respons host.' },
    { id: 24, question: 'Jika administrator ingin mencegah klien melakukan ping ke router, tindakan yang tepat adalah...', answer: 'a', options: ['A. Membuat firewall filter ICMP dengan action drop', 'B. Menambah semua IP ke DHCP', 'C. Menonaktifkan DNS', 'D. Menghapus gateway', 'E. Mematikan semua WiFi'], pembahasan: 'Memblokir ping dari klien dilakukan dengan firewall filter chain input, protokol ICMP, dengan action drop.' },
    { id: 25, question: 'Metode pemblokiran file berukuran besar seperti .mp3 biasanya dilakukan dengan...', answer: 'a', options: ['A. Firewall filter berdasarkan ekstensi atau content', 'B. Mengganti kartu jaringan', 'C. Menghapus DHCP', 'D. Menentukan NTP server', 'E. Menambah IP Pool'], pembahasan: 'Pemblokiran file besar seperti .mp3 umumnya memakai firewall filter berdasarkan ekstensi atau isi konten (content).' },
    { id: 26, question: 'Layer7 Protocol di MikroTik berguna untuk...', answer: 'a', options: ['A. Mengenali pola lalu lintas berdasarkan aplikasi atau protokol tertentu', 'B. Mengubah alamat IP', 'C. Menambah DNS client', 'D. Mengatur waktu router', 'E. Menghapus semua route default'], pembahasan: 'Layer7 Protocol mencocokkan pola lalu lintas (regex) untuk mengenali aplikasi atau protokol tertentu sebelum difilter.' },
    { id: 27, question: 'TLS Host pada firewall biasanya dipakai untuk memblokir lalu lintas berdasarkan...', answer: 'a', options: ['A. Nama host atau domain yang menggunakan TLS', 'B. Kecepatan processor', 'C. Jumlah port ethernet', 'D. Setting DHCP default', 'E. Koneksi hotspot'], pembahasan: 'TLS Host memfilter koneksi berdasarkan nama host/domain pada koneksi terenkripsi TLS (HTTPS).' },
    { id: 28, question: 'Web Proxy pada MikroTik biasanya digunakan untuk...', answer: 'a', options: ['A. Mengelola dan memfilter akses web melalui proxy server', 'B. Menyimpan semua perangkat jaringan', 'C. Mempercepat browser client', 'D. Menyalin file konfigurasi ke USB', 'E. Menyimpan log NTP'], pembahasan: 'Web Proxy meneruskan dan menyaring permintaan web sehingga akses dapat dikelola dan difilter.' },
    { id: 29, question: 'Tujuan utama firewall filter pada jaringan sekolah adalah...', answer: 'a', options: ['A. Menjaga keamanan dan membatasi akses yang tidak diinginkan', 'B. Menambah bandwidth siswa', 'C. Mengubah IP router', 'D. Menonaktifkan semua hotspot', 'E. Menjadikan router sebagai DNS'], pembahasan: 'Firewall menjaga keamanan jaringan dan membatasi akses yang tidak diinginkan sesuai kebijakan sekolah.' },
    { id: 30, question: 'Jika ingin memblokir situs tertentu agar tidak dapat dibuka, langkah yang paling tepat adalah...', answer: 'a', options: ['A. Menggunakan firewall, TLS Host, Layer7, atau proxy filtering', 'B. Mengatur NTP Client', 'C. Mengganti usernames hotspot', 'D. Menambahkan IP Public baru', 'E. Menghapus semua DNS static'], pembahasan: 'Situs dapat diblokir dengan kombinasi firewall filter, TLS Host, Layer7, atau filtering melalui Web Proxy.' },
    { id: 31, question: 'Berikut ini yang termasuk fungsi utama RouterOS adalah...', answer: 'a', options: ['A. Menjalankan layanan router, firewall, DHCP, dan hotspot', 'B. Membuat aplikasi desain grafis', 'C. Menyunting video', 'D. Mengolah data spreadsheet', 'E. Menyimpan foto kamera'], pembahasan: 'RouterOS adalah sistem operasi router yang menyediakan routing, firewall, DHCP, hotspot, dan layanan jaringan lainnya.' },
    { id: 32, question: 'Pengaturan DNS static pada MikroTik bertujuan untuk...', answer: 'a', options: ['A. Menambahkan pemetaan nama domain ke alamat IP tertentu', 'B. Menyalakan WiFi', 'C. Menambahkan user profile', 'D. Mengubah file .mp3', 'E. Menambah routing OSPF'], pembahasan: 'DNS Static menambahkan pemetaan manual nama domain ke alamat IP tertentu di router.' },
    { id: 33, question: 'Jika router menerima IP dari ISP secara otomatis melalui DHCP, berarti router tersebut menggunakan...', answer: 'a', options: ['A. DHCP Client', 'B. DHCP Server', 'C. Static Route', 'D. Proxy Cache', 'E. User Profile'], pembahasan: 'Menerima IP otomatis dari ISP berarti router berperan sebagai DHCP Client pada interface WAN.' },
    { id: 34, question: 'Kalau sebuah jaringan lokal memakai IP 192.168.10.0/24, maka gateway yang umum dipakai untuk router LAN adalah...', answer: 'a', options: ['A. 192.168.10.1', 'B. 192.168.10.255', 'C. 10.0.0.1', 'D. 8.8.8.8', 'E. 255.255.255.0'], pembahasan: 'Alamat pertama host (…1) umumnya dipakai sebagai gateway router pada jaringan 192.168.10.0/24, yaitu 192.168.10.1.' },
    { id: 35, question: 'Perintah atau fitur yang sering digunakan untuk memblokir akses website dengan sekumpulan pola yang mirip aplikasi tertentu adalah...', answer: 'a', options: ['A. Layer7 Protocol', 'B. NTP Client', 'C. DHCP Client', 'D. DNS Static', 'E. WinBox Login'], pembahasan: 'Layer7 Protocol digunakan untuk memblokir traffic berdasarkan pola yang menyerupai aplikasi atau protokol tertentu.' },
    { id: 36, question: 'Fungsi utama Web Proxy dalam konteks pembatasan akses adalah...', answer: 'a', options: ['A. Menyaring konten web yang diminta user', 'B. Menambah kapasitas RAM', 'C. Mempercepat pengiriman file .mp3', 'D. Mengubah bridge menjadi switch', 'E. Mengatur alamat NTP'], pembahasan: 'Web Proxy menyaring konten web yang diminta user sehingga akses yang tidak diinginkan dapat dibatasi.' },
    { id: 37, question: 'Penanda yang paling tepat untuk mengidentifikasi situs tertentu pada TLS adalah...', answer: 'a', options: ['A. TLS Host', 'B. IP Pool', 'C. DNS Client', 'D. NTP Server', 'E. DHCP Lease'], pembahasan: 'TLS Host menjadi penanda nama situs pada koneksi TLS/HTTPS sehingga filter dapat mengenali domain tujuan.' },
    { id: 38, question: 'Fungsi NAT pada router adalah untuk...', answer: 'a', options: ['A. Menerjemahkan IP private ke IP public agar bisa ke internet', 'B. Menentukan nama identitas router', 'C. Mengubah perangkat menjadi hotspot', 'D. Menyimpan jadwal NTP', 'E. Menambahkan user profile'], pembahasan: 'NAT menerjemahkan alamat IP privat ke IP publik sehingga client dapat terhubung ke internet.' },
    { id: 39, question: 'Jaringan lokal yang tidak memiliki IP publik dan memerlukan router untuk keluar internet dikenal sebagai...', answer: 'a', options: ['A. Jaringan privat', 'B. Jaringan publik', 'C. Jaringan modem', 'D. Jaringan WiFi hotspot', 'E. Jaringan bridge'], pembahasan: 'Jaringan privat memakai alamat IP internal dan memerlukan router serta NAT untuk terhubung ke internet.' },
    { id: 40, question: 'Hal yang paling tepat dilakukan saat router baru diaktifkan agar aman adalah...', answer: 'a', options: ['A. Mengganti identitas dan password admin', 'B. Langsung menghapus semua interface', 'C. Memasang firewall untuk semua port', 'D. Menyalakan semua layanan tanpa filter', 'E. Menghapus semua rule NAT'], pembahasan: 'Langkah keamanan pertama adalah mengganti identitas dan password admin default agar router tidak mudah diakses orang lain.' },
    { id: 61, question: 'Menu di WinBox untuk membuat password Wi-Fi (Security Profile) adalah...', answer: 'b', options: ['A. IP → DHCP Server', 'B. Wireless → Security Profiles', 'C. System → Identity', 'D. IP → Firewall → NAT', 'E. IP → Routes'], pembahasan: 'Keamanan Wi-Fi diatur melalui menu Wireless → Security Profiles, bukan pada DHCP Server atau Firewall.' },
    { id: 62, question: 'Pada Security Profile WLAN, Mode yang dipilih agar Wi-Fi menggunakan kata sandi WPA2 adalah...', answer: 'a', options: ['A. dynamic keys', 'B. static keys', 'C. none', 'D. open', 'E. 802.1x'], pembahasan: 'Mode dynamic keys digunakan untuk keamanan WPA/WPA2 agar client harus memasukkan kata sandi (Pre-Shared Key).' },
    { id: 63, question: 'Panjang minimal WPA2 Pre-Shared Key (password Wi-Fi) pada Security Profile adalah...', answer: 'b', options: ['A. 4 karakter', 'B. 8 karakter', 'C. 12 karakter', 'D. 16 karakter', 'E. 20 karakter'], pembahasan: 'WPA2 mewajibkan Pre-Shared Key (password Wi-Fi) minimal 8 karakter.' },
    { id: 64, question: 'Agar router dapat memancarkan sinyal Wi-Fi ke banyak perangkat, Mode interface wlan1 diubah menjadi...', answer: 'c', options: ['A. station', 'B. alignment only', 'C. ap bridge', 'D. nstreme slave', 'E. wds slave'], pembahasan: 'Mode ap bridge membuat wlan1 berperan sebagai access point yang melayani banyak perangkat klien.' },
    { id: 65, question: 'Nama jaringan Wi-Fi yang dipancarkan oleh router dikenal dengan istilah...', answer: 'b', options: ['A. MAC', 'B. SSID', 'C. PSK', 'D. Lease', 'E. Pool'], pembahasan: 'SSID adalah nama jaringan Wi-Fi yang dipancarkan dan tampil pada daftar WiFi perangkat client.' },
    { id: 66, question: 'Pada konfigurasi WLAN, alamat IP yang Valid untuk dipasang pada interface wlan adalah...', answer: 'a', options: ['A. 192.168.33.1/25', 'B. 192.168./24', 'C. 10.10.10.0/24', 'D. 172.16.0.1/16', 'E. 192.168.33.254'], pembahasan: '192.168.33.1/25 merupakan alamat host yang valid untuk interface wlan (bukan alamat network atau broadcast).' },
    { id: 67, question: 'Wizard yang dipakai untuk mengonfigurasi DHCP Server pada interface wlan adalah...', answer: 'd', options: ['A. Hotspot Setup', 'B. Quick Set', 'C. Neighbors', 'D. DHCP Setup', 'E. Backup Setup'], pembahasan: 'DHCP Setup adalah wizard yang digunakan untuk membuat DHCP server pada interface wlan secara cepat.' },
    { id: 68, question: 'Pada wizard DHCP Setup WLAN, Addresses to Give Out secara default untuk ip 192.168.33.1/25 akan terisi rentang alamat...', answer: 'a', options: ['A. 192.168.33.2 - 192.168.33.254', 'B. 192.168.33.0 - 192.168.33.1', 'C. 8.8.8.8 - 8.8.4.4', 'D. 172.32.1.1 - 172.32.1.70', 'E. 192.168.33.255 - 192.168.33.300'], pembahasan: 'Subnet /25 memiliki rentang host 192.168.33.1–192.168.33.254. Alamat pertama dipakai router, sehingga client mendapat 192.168.33.2–192.168.33.254.' },
    { id: 69, question: 'Lease Time default pada wizard DHCP Setup adalah...', answer: 'b', options: ['A. 1 jam', 'B. 3 jam', 'C. 24 jam', 'D. 7 hari', 'E. 1 menit'], pembahasan: 'Nilai default Lease Time pada wizard DHCP Setup MikroTik adalah 3 jam.' },
    { id: 70, question: 'Untuk melihat daftar perangkat klien yang terhubung ke Wi-Fi, menu yang dibuka adalah...', answer: 'e', options: ['A. IP → Routes', 'B. IP → Firewall', 'C. Wireless → Security Profiles', 'D. System → Users', 'E. IP → DHCP Server, tab Leases'], pembahasan: 'Daftar klien yang mendapat IP dari DHCP dapat dilihat pada menu IP → DHCP Server, tab Leases.' },
    { id: 71, question: 'Klien yang terhubung ke Wi-Fi pada contoh konfigurasi wlan akan mendapat alamat IP dalam rentang...', answer: 'a', options: ['A. 192.168.33.x', 'B. 8.8.8.x', 'C. 172.32.x.x', 'D. 10.0.0.x', 'E. 192.168.32.x'], pembahasan: 'Client yang terhubung ke SSID mendapat IP dari DHCP server wlan yang berada pada rentang 192.168.33.x (sesuai IP wlan 192.168.33.1/25).' },
    { id: 72, question: 'Agar klien dapat internet setelah terhubung ke SSID Wi-Fi, selain memancarkan sinyal diperlukan...', answer: 'b', options: ['A. firewall dengan action drop', 'B. pemasangan IP Address di wlan dan pengaktifan DHCP Server', 'C. mematikan Security Profile', 'D. mengganti Identity router', 'E. menonaktifkan NAT'], pembahasan: 'Agar klien mendapat IP dan koneksi, interface wlan harus dipasangi IP Address dan DHCP Server diaktifkan.' },
    { id: 73, question: 'MikroTik adalah perusahaan yang berasal dari negara...', answer: 'd', options: ['A. Jerman', 'B. Jepang', 'C. Amerika Serikat', 'D. Latvia', 'E. Tiongkok'], pembahasan: 'MikroTik adalah perusahaan asal negara Latvia (Riga), Eropa.' },
    { id: 74, question: 'Produk utama MikroTik terdiri atas...', answer: 'a', options: ['A. RouterOS dan RouterBOARD', 'B. Windows dan Linux', 'C. Cisco dan Juniper', 'D. hAP dan CCR', 'E. WinBox dan Putty'], pembahasan: 'Produk utama MikroTik adalah RouterOS (perangkat lunak router) dan RouterBOARD (perangkat keras router).' },
    { id: 75, question: 'Seri RouterBOARD yang cocok untuk kebutuhan jaringan besar / ISP adalah...', answer: 'b', options: ['A. RB750', 'B. CCR', 'C. hAP', 'D. Audience', 'E. hEX'], pembahasan: 'CCR (Cloud Core Router) dirancang untuk kebutuhan trafik tinggi, seperti yang dipakai ISP dan jaringan skala besar.' },
    { id: 76, question: 'Tipe RouterBOARD yang menggabungkan fungsi switching dan routing adalah...', answer: 'd', options: ['A. hAP ac2', 'B. RB750', 'C. Chateau', 'D. CRS', 'E. Audience'], pembahasan: 'CRS (Cloud Router Switch) memadukan fungsi switch dan routing dalam satu perangkat.' },
    { id: 77, question: 'Pengelolaan bandwidth pada RouterOS dilakukan menggunakan mekanisme...', answer: 'c', options: ['A. DNS Static', 'B. IP Pool', 'C. Queue (HTB/PCQ)', 'D. Security Profile', 'E. Neighbor Discovery'], pembahasan: 'Bandwidth dikelola pada RouterOS menggunakan Queue dengan mekanisme HTB atau PCQ.' },
    { id: 78, question: 'Pada konfigurasi dasar di referensi, komputer dihubungkan ke router melalui port...', answer: 'a', options: ['A. ether2 (LAN)', 'B. ether1 (WAN)', 'C. ether4', 'D. ether5', 'E. wlan1'], pembahasan: 'Pada referensi modul, komputer client dihubungkan ke router melalui ether2 sebagai interface LAN.' },
    { id: 79, question: 'Teknik yang memungkinkan banyak perangkat LAN berbagi satu IP publik untuk akses internet adalah...', answer: 'b', options: ['A. DHCP Pool', 'B. NAT', 'C. Layer7 Protocol', 'D. SNTP', 'E. WinBox'], pembahasan: 'NAT (misalnya source NAT masquerade) memungkinkan banyak perangkat LAN berbagi satu IP publik saat mengakses internet.' },
    { id: 80, question: 'DNS Redirect pada NAT berfungsi untuk...', answer: 'e', options: ['A. mempercepat video streaming', 'B. memblokir file .mp3', 'C. menambah IP publik', 'D. menyimpan log login', 'E. memaksa lalu lintas DNS klien lewat MikroTik agar tidak bisa mengganti DNS manual'], pembahasan: 'DNS Redirect mengalihkan seluruh permintaan DNS klien agar selalu lewat router sehingga DNS tidak bisa diganti secara manual.' }
];

function hashString(value) {
    let hash = 0;
    for (let i = 0; i < value.length; i++) {
        hash = (hash * 31 + value.charCodeAt(i)) >>> 0;
    }
    return hash;
}

function seedRandom(seedValue) {
    let state = seedValue >>> 0;
    return function () {
        state = (state + 0x6D2B79F5) >>> 0;
        let t = state;
        t = Math.imul(t ^ (t >>> 15), t | 1);
        t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
        return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
}

function getAssignedQuestionIds(nis) {
    const ids = QUESTION_BANK.map((item) => item.id);
    const rand = seedRandom(hashString(String(nis)));

    for (let i = ids.length - 1; i > 0; i--) {
        const j = Math.floor(rand() * (i + 1));
        [ids[i], ids[j]] = [ids[j], ids[i]];
    }

    return ids.slice(0, STUDENT_QUESTION_COUNT);
}